auth/urls.py
from django.urls import re_path
from . import views


app_name = "auth"
urlpatterns = [
    re_path(r"^$", views.List.as_view(), name="list"),
    re_path(r"^edit/(?P<user>[^/]+)$", views.Edit.as_view(), name="edit"),
]

octonet/urls.py
from django.conf.urls import include
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r"^$", views.Home.as_view(), name="home"),
    re_path(r"^login/$", views.Login.as_view(), name="login"),
    re_path(r"^logout/$", views.Logout.as_view(), name="logout"),
    re_path(r"^newsfeed/$", views.NewsFeed.as_view(), name="newsfeed"),
    re_path(r"^veyon/client_conf$", views.VeyonClientConfiguration.as_view(), name="veyon-client-conf"),
    re_path(r"^octofussd-error/$", views.OctofussdError.as_view(), name="octofussd_error"),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r"^hostqueue/", include("hostqueue.urls", namespace="hostqueue")),
    re_path(r"^dhcp/", include("dhcp.urls", namespace="dhcp")),
    re_path(r"^polygen/", include("polygen.urls", namespace="polygen")),
    re_path(r"^firewall/", include("firewall.urls", namespace="firewall")),
    re_path(r"^dansguardian/", include("dansguardian.urls", namespace="dansguardian")),
    re_path(r"^host/", include("host.urls", namespace="host")),
    re_path(r"^upgrade/", include("upgrade.urls", namespace="upgrade")),
    re_path(r"^asterisk/", include("asterisk.urls", namespace="asterisk")),
    re_path(r"^samba/", include("samba.urls", namespace="samba")),
    re_path(r"^users/", include("users.urls", namespace="users")),
    re_path(r"^script/", include("script.urls", namespace="script")),
    re_path(r"^quota/", include("quota.urls", namespace="quota")),
    re_path(r"^printers/", include("printers.urls", namespace="printers")),
    re_path(r"^services/", include("services.urls", namespace="services")),
    re_path(r"^auth/", include("auth.urls", namespace="auth")),
    re_path(r"^fussmanager/", include("fussmanager.urls", namespace="fussmanager")),
]

quota/urls.py
from django.urls import re_path
from . import views


app_name = "quota"
urlpatterns = [
    re_path(r"^$", views.List.as_view(), name="list"),
    re_path(r"^edit/(?P<fs>[^/]+)$", views.Edit.as_view(), name="edit"),
    re_path(r"^edit/(?P<fs>[^/]+)/save$", views.Save.as_view(), name="save"),
]

quota/models.py
from django.db import models

# Create your models here.

quota/views.py
from django import http
from django.views.generic import View
from django.views.generic import TemplateView
from octonet.mixins import OctonetMixin


class List(OctonetMixin, TemplateView):
    template_name = "quota/list.html"

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        # refs #161
        quota_filesystems = self.root_tree.llist(["quota"])
        serverinfo_filesystems = self.root_tree.lget(["serverinfo", "filesystems"])
        seen = set()
        filesystems = []
        # Get all filesystems, in quota and in serverinfo, and show % if there is a match,
        # otherwise show a "-"
        for fs in list(serverinfo_filesystems.keys()) + quota_filesystems:
            # The code in here is cop/pasted from mangle_fs_names() in the quota octofussd plugin
            # FIXME: Maybe a refactor in octofussd is needed, but it will break the GTK client.
            # FIXME: Maybe use quote_plus/unquote_plus that is reproducible in both ways? The
            # existing algorithm is dependant on the sorting order in /etc/fstab, or on the quirks
            # systemd maybe, and it's not predictable nor reversable (because of the numbers added
            # if a mangled name is already seen)
            # Turn it into a name that fits in the octofuss tree
            name = fs.strip("/").replace("/", "-")
            if name == "": name = "root"
            # Prevent collisions after mangling
            cand = name
            idx = 0
            while cand in seen:
                idx += 1
                cand = name + str(idx)
            if fs in serverinfo_filesystems:
                percentage = "%d%%" % int(serverinfo_filesystems[fs])
            else:
                percentage = "-"
            filesystems.append({
                'fs': fs,
                'mangled_fs': cand,
                'percentage': percentage,
            })
        ctx['filesystems'] = filesystems
        return ctx


class FSMixin(OctonetMixin):
    def load_objects(self):
        super().load_objects()
        self.fs = self.kwargs["fs"]

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        ctx["fs"] = self.fs
        return ctx


class Edit(FSMixin, TemplateView):
    template_name = "quota/edit.html"

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        ctx["quota_user"] = self.root_tree.lget(["quota", self.fs, "user"])
        ctx["quota_group"] = self.root_tree.lget(["quota", self.fs, "group"])
        return ctx


class Save(FSMixin, View):
    def post(self, request, *args, **kw):
        ugtype = request.POST["ugtype"]
        if ugtype not in ("user", "group"):
            return http.JsonResponse({"status": "invalid user/group type"})
        name = request.POST["name"]
        if "/" in name or name.startswith("."):
            return http.JsonResponse({"status": "invalid user/group name"})
        type = request.POST["type"]
        if type not in ("disk_soft", "disk_hard", "file_soft", "file_hard"):
            return http.JsonResponse({"status": "invalid quota type"})
        value = int(request.POST["value"])
        self.root_tree.lset(["quota", self.fs, ugtype, name, type], value)
        return http.JsonResponse({"status": "ok"})

quota/templates/quota/edit.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block head %}
{{block.super}}
<link rel="stylesheet" href="{% static 'dt/datatables.min.css' %}"/>
<script src="{% static 'dt/datatables.min.js' %}"></script>

<script type="text/javascript">
    (function($){
        "use strict";

        // From jQuery.ui.keyCode
        var keycode = {
            BACKSPACE: 8,
            COMMA: 188,
            DELETE: 46,
            DOWN: 40,
            END: 35,
            ENTER: 13,
            ESCAPE: 27,
            HOME: 36,
            LEFT: 37,
            PAGE_DOWN: 34,
            PAGE_UP: 33,
            PERIOD: 190,
            RIGHT: 39,
            SPACE: 32,
            TAB: 9,
            UP: 38
        };

        var popup_cell;
        var popup_ugtype;
        var popup_name;
        var popup_type;
        var popup_submitted;
        var popup_index_map = {
            2: "disk_soft",
            3: "disk_hard",
            5: "file_soft",
            6: "file_hard",
        };

        function open_edit_dialog(cell)
        {
            popup_cell = $(cell);
            popup_submitted = false;
            popup_ugtype = popup_cell.parents("table").first().attr("id") == "user_table" ? "user" : "group";
            popup_name = popup_cell.parent().children("td").first().text();
            popup_type = popup_index_map[popup_cell.index()];
            $("#edit_value").val(popup_cell.text());
            $("#edit_dialog").modal('show');
        }

        function close_edit_dialog()
        {
            if (popup_submitted)
            {
                var value = $("#edit_value").val();
                console.log("SAVE", popup_ugtype, popup_name, popup_type, value);
                $.ajax({
                    url: "{% url 'quota:save' fs=fs %}",
                    method: "POST",
                    success: function(data, textStatus, jqXHR) {
                        if (data.status != "ok")
                            inject_message('#id_messages', 'danger', data.status);
                    },
                    data: {
                        ugtype: popup_ugtype,
                        name: popup_name,
                        type: popup_type,
                        value: value,
                    },
                    error: function(jqXHR, textStatus, errorThrown) {
                        console.error(jqXHR, textStatus, errorThrown);
                        inject_message('#id_messages', 'danger', jqXHR.responseText);
                    },
                });
                popup_cell.text(value);
            }
            popup_cell.focus();
        }

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        function main()
        {
            // Set csrf token automatically in ajax requests
            // see https://docs.djangoproject.com/en/1.8/ref/csrf/#ajax
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", "{{csrf_token}}");
                    }
                }
            });

            $("#user_table").DataTable({
                language: {
                    url:  "{% static 'dt/i18n/' %}{{LANGUAGE_CODE}}.lang"
                },
                pageLength: 25,
                order: [[1, "asc"]],
            });

            $("#group_table").DataTable({
                language: {
                    url:  "{% static 'dt/i18n/' %}{{LANGUAGE_CODE}}.lang"
                },
                pageLength: 25,
                order: [[1, "asc"]],
            });
            $("td.edit").dblclick(function(evt) {
                open_edit_dialog(this);
            });
            $("td.edit").keydown(function(evt) {
                if (evt.which == keycode.ENTER)
                {
                    open_edit_dialog(this);
                } else if (evt.which == keycode.UP) {
                    evt.preventDefault();
                    var index = $(this).index();
                    $($(this).parent().prev().children("td")[index]).focus();
                } else if (evt.which == keycode.DOWN) {
                    evt.preventDefault();
                    var index = $(this).index();
                    $($(this).parent().next().children("td")[index]).focus();
                } else if (evt.which == keycode.LEFT) {
                    evt.preventDefault();
                    var siblings = $(this).parent().children("td.edit");
                    var index;
                    for (var i = 0; i < siblings.length; ++i)
                        if (siblings[i] == this)
                    {
                        index = i;
                        break;
                    }
                    if (index == 0)
                        $(this).parent().prev().children("td.edit").last().focus();
                    else
                        $(siblings[index - 1]).focus();
                } else if (evt.which == keycode.RIGHT) {
                    $(this).next("td.edit").focus();
                    var siblings = $(this).parent().children("td.edit");
                    var index;
                    for (var i = 0; i < siblings.length; ++i)
                        if (siblings[i] == this)
                    {
                        index = i;
                        break;
                    }
                    if (index == siblings.length - 1)
                        $(this).parent().next().children("td.edit").first().focus();
                    else
                        $(siblings[index + 1]).focus();
                }
            });

            $("#edit_form").submit(function(evt) {
                evt.preventDefault();
                popup_submitted = true;
                $("#edit_dialog").modal("hide");
                return false;
            });

            $("#edit_dialog").on("shown.bs.modal", function(evt) {
                $("#edit_value").focus();
            });

            $("#edit_dialog").on("hide.bs.modal", function(evt) {
                if (document.activeElement.id == "edit_save")
                    popup_submitted = true;
                close_edit_dialog();
            });

            $("#edit_dialog").on("hidden.bs.modal", function(evt) {
                popup_cell.focus();
            });
        }

        $(main);
    })(jQuery);
</script>

<style>
  table td:focus { border-color: red; background-color: #E3C4C3; }
</style>
{% endblock head %}

{% block title %}{% blocktrans with fs=fs %}Quota for {{fs}}{% endblocktrans %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>{% blocktrans with fs=fs %}Quota for {{fs}}{% endblocktrans %}</h1>

    <div class="modal fade" tabindex="-1" role="dialog" id="edit_dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"
                    aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title">{% trans "Edit value" %}</h4>
          </div>
          <div class="modal-body">
            <form id="edit_form">
              <label for="value">{% trans "New value:" %}
                <input id="edit_value" name="value" value="">
              </label>
            </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
              {% trans "Cancel" %}
            </button>
            <button type="button" class="btn btn-primary" data-dismiss="modal"
                    id="edit_save">
              {% trans "Save" %}
            </button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    <p>You can edit the quotas by selecting the cell with the mouse. Pressing
    "ENTER" or double cliking the cell will allows you to edit the value, and
    arrow keys allows to navigate through the table.</p>
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#user" aria-controls="user" role="tab" data-toggle="tab">
          {% trans "User" %}
        </a>
      </li>
      <li role="presentation">
        <a href="#group" aria-controls="group" role="tab" data-toggle="tab">
          {% trans "Group" %}
        </a>
      </li>
    </ul>

    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="user">

        <table class="table table-striped" id="user_table">
          <thead>
            <tr>
              <th>{% trans "User" %}</th>
              <th>{% trans "Disk used" %}</th>
              <th>{% trans "Disk quota soft" %}</th>
              <th>{% trans "Disk quota hard" %}</th>
              <th>{% trans "File used" %}</th>
              <th>{% trans "File quota soft" %}</th>
              <th>{% trans "File quota hard" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for u in quota_user %}
            <tr>
              <td>{{u.name}}</td>
              <td>{{u.disk_used}}</td>
              <td class="edit" tabindex="0">{{u.disk_soft}}</td>
              <td class="edit" tabindex="0">{{u.disk_hard}}</td>
              <td>{{u.file_used}}</td>
              <td class="edit" tabindex="0">{{u.file_soft}}</td>
              <td class="edit" tabindex="0">{{u.file_hard}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      <div role="tabpanel" class="tab-pane" id="group">

        <table class="table table-striped" id="group_table">
          <thead>
            <tr>
              <th>{% trans "Group" %}</th>
              <th>{% trans "Disk used" %}</th>
              <th>{% trans "Disk quota soft" %}</th>
              <th>{% trans "Disk quota hard" %}</th>
              <th>{% trans "File used" %}</th>
              <th>{% trans "File quota soft" %}</th>
              <th>{% trans "File quota hard" %}</th>
            </tr>
          </thead>
          <tbody>
            {% for g in quota_group %}
            <tr>
              <td>{{g.name}}</td>
              <td>{{g.disk_used}}</td>
              <td class="edit" tabindex="0">{{g.disk_soft}}</td>
              <td class="edit" tabindex="0">{{g.disk_hard}}</td>
              <td>{{g.file_used}}</td>
              <td class="edit" tabindex="0">{{g.file_soft}}</td>
              <td class="edit" tabindex="0">{{g.file_hard}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

quota/templates/quota/list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "File system with quotas" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>{% trans "List of file systems" %}</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>{% trans "Filesystem" %}</th>
          <th>{% trans "Used space" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for fs in filesystems %}
        <tr>
          <td><a href="{% url 'quota:edit' fs=fs.mangled_fs %}">{{fs.fs}}</a></td>
          <td>{{fs.percentage}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}