auth/urls.py
from django.urls import re_path
from . import views


app_name = "auth"
urlpatterns = [
    re_path(r"^$", views.List.as_view(), name="list"),
    re_path(r"^edit/(?P<user>[^/]+)$", views.Edit.as_view(), name="edit"),
]

octonet/urls.py
from django.conf.urls import include
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r"^$", views.Home.as_view(), name="home"),
    re_path(r"^login/$", views.Login.as_view(), name="login"),
    re_path(r"^logout/$", views.Logout.as_view(), name="logout"),
    re_path(r"^newsfeed/$", views.NewsFeed.as_view(), name="newsfeed"),
    re_path(r"^veyon/client_conf$", views.VeyonClientConfiguration.as_view(), name="veyon-client-conf"),
    re_path(r"^octofussd-error/$", views.OctofussdError.as_view(), name="octofussd_error"),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r"^hostqueue/", include("hostqueue.urls", namespace="hostqueue")),
    re_path(r"^dhcp/", include("dhcp.urls", namespace="dhcp")),
    re_path(r"^polygen/", include("polygen.urls", namespace="polygen")),
    re_path(r"^firewall/", include("firewall.urls", namespace="firewall")),
    re_path(r"^dansguardian/", include("dansguardian.urls", namespace="dansguardian")),
    re_path(r"^host/", include("host.urls", namespace="host")),
    re_path(r"^upgrade/", include("upgrade.urls", namespace="upgrade")),
    re_path(r"^asterisk/", include("asterisk.urls", namespace="asterisk")),
    re_path(r"^samba/", include("samba.urls", namespace="samba")),
    re_path(r"^users/", include("users.urls", namespace="users")),
    re_path(r"^script/", include("script.urls", namespace="script")),
    re_path(r"^quota/", include("quota.urls", namespace="quota")),
    re_path(r"^printers/", include("printers.urls", namespace="printers")),
    re_path(r"^services/", include("services.urls", namespace="services")),
    re_path(r"^auth/", include("auth.urls", namespace="auth")),
    re_path(r"^fussmanager/", include("fussmanager.urls", namespace="fussmanager")),
]

script/urls.py
from django.urls import re_path
from . import views


app_name = "script"
urlpatterns = [
    re_path(r"^$", views.List.as_view(), name="list"),
    re_path(r"^create$", views.Create.as_view(), name="create"),
    re_path(r"^edit/(?P<name>[^/]+)$", views.Edit.as_view(), name="edit"),
    re_path(r"^runs/(?P<name>[^/]+)$", views.ListRuns.as_view(), name="list_runs"),
    re_path(r"^runs/(?P<name>[^/]+)/edit/(?P<run>[^/]+)$", views.EditRun.as_view(), name="edit_run"),
    re_path(r"^runs/(?P<name>[^/]+)/edit/(?P<run>[^/]+)/delete$", views.DeleteRun.as_view(), name="delete_run"),
    re_path(r"^runs/(?P<name>[^/]+)/edit/(?P<run>[^/]+)/schedule$", views.Schedule.as_view(), name="schedule_run"),
    re_path(r"^runs/(?P<name>[^/]+)/edit/(?P<run>[^/]+)/remove-host$", views.RemoveHost.as_view(), name="edit_run_remove_host"),
]

upgrade/urls.py
from django.urls import re_path
from . import views

app_name = "upgrade"
urlpatterns = [
    re_path(r"^$", views.List.as_view(), name="list"),
    re_path(r"^edit/(?P<name>[^/]+)$", views.Edit.as_view(), name="edit"),
    re_path(r"^schedule/(?P<name>[^/]+)$", views.Schedule.as_view(), name="schedule"),
    re_path(r"^delete/(?P<name>[^/]+)$", views.Delete.as_view(), name="delete"),
    re_path(r"^update/(?P<name>[^/]+)$", views.Update.as_view(), name="update"),
    re_path(r"^complete/(?P<domain>[^/]+)$", views.Complete.as_view(), name="complete"),
    re_path(r"^hosts/add/(?P<name>[^/]+)$", views.AddHost.as_view(), name="add_host"),
    re_path(r"^hosts/remove/(?P<name>[^/]+)$", views.RemoveHost.as_view(), name="remove_host"),
    re_path(r"^hosts/addgroup/(?P<name>[^/]+)$", views.AddGroup.as_view(), name="add_group"),
    re_path(r"^hosts/removegroup/(?P<name>[^/]+)$", views.RemoveGroup.as_view(), name="remove_group"),
]

script/models.py
from django.db import models

# Create your models here.

script/views.py
from django.utils.translation import gettext_lazy as _
from django import http, forms
from django.utils import html
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import View
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.contrib import messages
from octonet.mixins import OctonetMixin
from octonet.forms import FormControlClassMixin
from urllib.parse import quote_plus, unquote_plus


class List(OctonetMixin, TemplateView):
    template_name = "script/list.html"

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        scripts = self.root_tree.lget(["scripts"])
        scripts.sort(key = lambda x:x["name"])
        for s in scripts:
            if s["runs"]:
                s["completed_percent"] = "{}%".format(round(sum(1 for x in s["runs"] if x["completed"] is not None) / len(s["runs"]) * 100))
            else:
                s["completed_percent"] = "--"
        ctx["scripts"] = scripts
        return ctx


class ScriptMixin(OctonetMixin):
    def load_objects(self):
        super().load_objects()
        self.tree = self.octofuss_tree("/scripts/{}".format(self.kwargs["name"]))
        self.script = self.tree.lget([])

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        ctx["script"] = self.script
        return ctx

    def get_initial(self):
        return self.script

    def get_success_url(self):
        return reverse("script:list")
    

class ScriptEditForm(FormControlClassMixin, forms.Form):
    script = forms.CharField(required=False, label=_("Script code"), widget=forms.Textarea(attrs={"rows": 25, "cols": 80, "wrap": "off"}))
    upload = forms.FileField(required=False, label=_("Upload script"))

    def clean(self):
        script = self.cleaned_data["script"]
        upload = self.cleaned_data["upload"]

        if not script and not upload:
            self.add_error(
                    "script",
                    forms.ValidationError(_("Please type the script or upload a file"), code="script_missing")
            )
            self.add_error(
                    "upload",
                    forms.ValidationError(_("Please type the script or upload a file"), code="script_missing")
            )

        return self.cleaned_data

    def clean_upload(self):
        f = self.cleaned_data["upload"]
        if f is not None and f.size > 1000000:
            raise forms.ValidationError(_("Script file is too big"), code="script_too_big")
        return f


class ScriptCreateForm(ScriptEditForm):
    name = forms.CharField(label=_("Script name"))


class Create(OctonetMixin, FormView):
    template_name = "script/edit.html"
    form_class = ScriptCreateForm

    def get_success_url(self):
        return reverse("script:list")

    def form_valid(self, form):
        script_file = form.cleaned_data["upload"]
        if script_file is None:
            script = form.cleaned_data["script"]
        else:
            script = script_file.read().decode('utf-8')
        path = ["scripts", form.cleaned_data["name"]]
        self.root_tree.lcreate(path)
        self.root_tree.lset(path + ["script"], script)
        return super().form_valid(form)


class Edit(ScriptMixin, FormView):
    template_name = "script/edit.html"
    form_class = ScriptEditForm

    def form_valid(self, form):
        script_file = form.cleaned_data["upload"]
        if script_file is None:
            script = form.cleaned_data["script"]
        else:
            script = script_file.read().decode('utf-8')
        self.tree.lset(["script"], script)
        return super().form_valid(form)


class NewRunForm(FormControlClassMixin, forms.Form):
    name = forms.CharField(label=_("Name"))


class ListRuns(ScriptMixin, FormView):
    template_name = "script/list_runs.html"
    form_class = NewRunForm

    def get_initial(self):
        return {}

    def get_context_data(self, **kw):
        ctx = super().get_context_data()
        for run in ctx["script"]["runs"]:
            finished = [k for k in run["hosts"] if k["ended"]]
            run["finished_hosts"] = len(finished)
            run["errored_hosts"] = len([k for k in finished if k["result"] != 0])
        return ctx


    def get_success_url(self):
        return reverse("script:list_runs", args=[self.script["name"]])
    
    def form_valid(self, form):
        name = quote_plus(form.cleaned_data["name"])
        self.root_tree.lcreate(["scripts", self.script["name"], "runs", name])
        return super().form_valid(form)


class RunMixin(ScriptMixin):
    def load_objects(self):
        super().load_objects()
        self.run = self.tree.lget(["runs", self.kwargs["run"]])

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        ctx["run"] = self.run
        return ctx

    def get_success_url(self):
        return reverse("script:edit_run", args=[self.script["name"], self.run["name"]])


class EditRunForm(FormControlClassMixin, forms.Form):
    add_host = forms.CharField(required=False, label=_("Add host"))
    add_group = forms.CharField(required=False, label=_("Add group"))
    del_group = forms.CharField(required=False, label=_("Remove group"))


class EditRun(RunMixin, FormView):
    template_name = "script/edit_run.html"
    form_class = EditRunForm

    def form_valid(self, form):
        add_host = form.cleaned_data["add_host"]
        if add_host:
            self.root_tree.lcreate(["scripts", self.script["name"], "runs", self.run["name"], "hosts", add_host])

        add_group = form.cleaned_data["add_group"]
        if add_group:
            for host in self.root_tree.llist(["cluster", add_group]):
                if host.startswith(":"): continue
                self.root_tree.lcreate(["scripts", self.script["name"], "runs", self.run["name"], "hosts", host])

        del_group = form.cleaned_data["del_group"]
        if del_group:
            for host in self.root_tree.llist(["cluster", del_group]):
                if host.startswith(":"): continue
                path = ["scripts", self.script["name"], "runs", self.run["name"], "hosts", host]
                if self.root_tree.lhas(path):
                    self.root_tree.ldelete(path)

        return super().form_valid(form)


class RemoveHost(RunMixin, View):
    def post(self, request, *args, **kw):
        host = request.POST.get("host", None)
        if host:
            path = ["scripts", self.script["name"], "runs", self.run["name"], "hosts", host]
            if self.root_tree.lhas(path):
                self.root_tree.ldelete(path)
        return redirect("script:edit_run", name=self.script["name"], run=self.run["name"])
        

class DeleteRun(RunMixin, View):
    def post(self, request, *args, **kw):
        if self.run and (not self.run["scheduled"] or self.run["completed"]):
            path = ["scripts", self.script["name"], "runs", self.run["name"]]
            if self.root_tree.lhas(path):
                self.root_tree.ldelete(path)
        return redirect("script:list_runs", name=self.script["name"])


class Schedule(RunMixin, View):
    def post(self, request, *args, **kw):
        if not self.run["hosts"]:
            messages.error(self.request, _("Cannot schedule a script run without hosts"))
            return redirect("script:edit_run", name=self.script["name"], run=self.run["name"])
        if self.run["scheduled"]:
            messages.error(self.request, _("This run has already been scheduled"))
            return redirect("script:edit_run", name=self.script["name"], run=self.run["name"])

        self.root_tree.lset(["scripts", self.script["name"], "runs", self.run["name"], "scheduled"], True)

        return redirect("script:list_runs", name=self.script["name"])

script/templates/script/edit.html
{% extends "script/script_base.html" %}
{% load static %}
{% load i18n %}

{% block head %}
{{block.super}}
<script src="{% static 'edit_area/edit_area_full.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function() {
        editAreaLoader.init({
            id: "id_script",
            start_highlight: true,
            allow_resize: "both",
            allow_toggle: true,
            word_wrap: true,
            language: "en",
            syntax: "basic",
        });
    });
  </script>
{% endblock head %}

{% block title %}
{% if script %}
  {% blocktrans with name=script.name %}Edit script {{name}}{% endblocktrans %}
{% else %}
  {% trans "Create new script" %}
{% endif %}
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>
      {% if script %}
        {% blocktrans with name=script.name %}Edit script {{name}}{% endblocktrans %}
      {% else %}
        {% trans "Create new script" %}
      {% endif %}
    </h1>

    <form action="{{request.get_full_path}}" method="post"
          enctype="multipart/form-data">
      {% csrf_token %}
      <table class="table table-striped">
        {{form.as_table}}
        <tr>
          <td colspan="2">
            <button class="btn btn-primary"
                    type="submit">
              {% trans "Save" %}
            </button>
          </td>
        </tr>
      </table>
    </form>

  </div>
</div>
{% endblock %}

script/templates/script/edit_run.html
{% extends "script/script_base.html" %}
{% load static %}
{% load i18n %}
{% load utility_tags %}

{% block head %}
{{block.super}}
<script src="{% static 'typeahead-0.11.1/typeahead.bundle.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/typeaheadjs.css' %}"/>
<link rel="stylesheet" href="{% static 'dt/datatables.min.css' %}"/>
<script src="{% static 'dt/datatables.min.js' %}"></script>

<style type="text/css">
form.removehost {
  display: inline;
}
</style>
<script type="text/javascript">
(function($) {
"use strict";

function main()
{
  var hosts = new Bloodhound({
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    datumTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
      url: "{% url 'upgrade:complete' domain='hosts' %}",
      transform: function(response) {
        return $.map(response.names, function(name) {
          return { value: name };
        });
      },
    },
  });

  var groups = new Bloodhound({
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    datumTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
      url: "{% url 'upgrade:complete' domain='groups' %}",
      transform: function(response) {
        return $.map(response.names, function(name) {
          return { value: name };
        });
      },
    },
  });

  $("#id_add_host").typeahead({
    minLength: 1,
    highlight: true,
  }, {
    name: "hosts",
    source: hosts,
    display: 'value',
  });

  $("#id_add_group").typeahead({
    minLength: 1,
    highlight: true,
  }, {
    name: "groups",
    source: groups,
    display: 'value',
  });

  $("#id_del_group").typeahead({
    minLength: 1,
    highlight: true,
  }, {
    name: "groups",
    source: groups,
    display: 'value',
  });
}

$(main);
})(jQuery);
</script>
{% endblock %}

{% block title %}{% blocktrans with name=script.name|unquote_plus run=run.name|unquote_plus %}Edit run {{run}} of script {{name}}{% endblocktrans %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-9">
    <h1>{% blocktrans with name=script.name|unquote_plus run=run.name|unquote_plus %}Edit run {{run}} of script {{name}}{% endblocktrans %}</h1>    
  </div>
  <div class="col-md-3">
    {% if not run.scheduled or run.completed %}
    <form
       action="{% url 'script:delete_run' name=script.name run=run.name %}"
       method="post">
      {% csrf_token %}
      <button class="btn btn-primary btn-danger"
              type="submit">
        <span class="fa fa-times"></span>
        {% trans "Delete" %}
      </button>
    </form>
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <p>
    {% if run.scheduled %}
        <span class="label label-info">{% blocktrans with time=run.scheduled %}Scheduled at <b>{{time}}</b>{% endblocktrans %}</span>
      {% elif run.hosts %}
        <form action="{% url 'script:schedule_run' name=script.name run=run.name %}" method="post">{% csrf_token %}
          <button class="btn btn-primary btn-sm"
                  type="submit">
            <span class="fa fa-plus"></span>
            {% trans "Schedule" %}
          </button>
        </form>
        {% endif %}
        {% if run.scheduled %}
        {% if run.completed %}
        <span class="label label-success">{% blocktrans with time=run.completed %}Completed at <b>{{time}}</b>{% endblocktrans %}</span>
        {% else %}
        <span class="label label-danger">{% trans "Not completed yet" %}</span>
        {% endif %}
        {% endif %}
    </p>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    {% if not run.scheduled %}
    <form action="{{request.get_full_path}}" method="post">{% csrf_token %}
      {{form.as_p}}
          <button class="btn btn-primary btn-success" type="submit">
            <span class="fa fa-check"></span>
            {% trans "Confirm" %}
          </button>
    </form>
    {% endif %}
  </div>
  {% if not run.scheduled %}
  <div class="col-md-6">
    <h2>{% trans "Host list" %}</h2>
    
    <table class="table table-striped">
      {% for host in run.hosts %}
      <tr>
        <td>
          {{host.name}}
        </td>
        <td>
          <form class="removehost"
                action="{% url 'script:edit_run_remove_host' name=script.name run=run.name %}"
                method="post">
            {% csrf_token %}
            <input type="hidden" name="host" value="{{host.name}}">
            <button class="btn btn-danger btn-sm" type="submit">
              <span class="fa fa-times"></span>
              {% trans "Remove" %}
            </button>
          </form>
        </td>
      </tr>
      {% empty %}
      <tr class="danger">
        <td colspan="2" class="danger text-center">
          {% trans "There are no hosts in this run yet." %}
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>
  {% else %}
  
  <div class="col-md-12">
    <h2>{% trans "Host list" %}</h2>
    
    <script type="text/javascript">
      $(document).ready(function() {
          $("#host_list").DataTable({
              language: {
                  url:  "{% static 'dt/i18n/' %}{{LANGUAGE_CODE}}.lang"
              }
          });
      });
    </script>
    <table class="table table-striped" id="host_list">
      <thead>
        <tr>
          <th>Name</th>
          <th>Started</th>
          <th>Ended</th>
          <th>Result</th>
          <th>Output</th>
        </tr>
      </thead>
      <tbody>
        {% for host in run.hosts %}
        <tr>
          <td>{{host.name}}</td>
          <td>{{host.started|default:"--"}}</td>
          <td>{{host.ended|default:"--"}}</td>
          <td>
            {% if host.result == 0 %}
            {% trans "Ok" %}
            {% else %}
            {{host.result|default:"--"}}
            {% endif %}
          </td>
          <td>{{host.output}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endif %}
</div>
{% endblock %}

script/templates/script/list.html
{% extends "script/script_base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Scripts list" %}{% endblock %}

{% block head %}
{{block.super}}
<link rel="stylesheet" href="{% static 'dt/datatables.min.css' %}"/>
<script src="{% static 'dt/datatables.min.js' %}"></script>
{% endblock head %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>{% trans "List of scripts" %}</h1>
    <script type="text/javascript">
      $(document).ready(function() {
          $("#script_list").DataTable({
              language: {
                  url:  "{% static 'dt/i18n/' %}{{LANGUAGE_CODE}}.lang"
              }
          });
      });
    </script>
    <table class="table table-striped" id="script_list">
      <thead>
        <tr>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Completed runs" %}</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for script in scripts %}
        <tr>
          <td><a href="{% url 'script:edit' name=script.name %}">{{script.name}}</a></td>
          <td>{{script.completed_percent}}</td>
          <td>
            <a class="btn btn-sm btn-primary"
               href="{% url 'script:list_runs' name=script.name %}">
              <span class="fa fa-clock-o"></span>
              {% trans "Schedule" %}
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>


  </div>
</div>
{% endblock %}

script/templates/script/list_runs.html
{% extends "script/script_base.html" %}
{% load static %}
{% load i18n %}
{% load utility_tags %}

{% block title %}{% blocktrans with name=script.name %}List of runs for script {{name}}{% endblocktrans %}{% endblock %}

{% block head %}
{{block.super}}
<link rel="stylesheet" href="{% static 'dt/datatables.min.css' %}"/>
<script src="{% static 'dt/datatables.min.js' %}"></script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>{% blocktrans with name=script.name %}List of runs for script {{name}}{% endblocktrans %}</h1>

    {% if not script.runs %}
    <p>{% trans "There are no runs for this script" %}</p>
    {% else %}
    <script type="text/javascript">
    $(document).ready(function() {
        $("#run_list").DataTable({
            language: {
                url:  "{% static 'dt/i18n/' %}{{LANGUAGE_CODE}}.lang"
            }

        });
    });
    </script>
    <table class="table table-striped" id="run_list">
      <thead>
        <tr>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Scheduled" %}</th>
          <th>{% trans "Completed" %}</th>
          <th>{% trans "Total hosts / Completed / Errors" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for run in script.runs %}
        <tr>
          <td><a href="{% url 'script:edit_run' name=script.name run=run.name %}">{{run.name|unquote_plus}}</a></td>
          <td>{{run.scheduled|default:"--"}}</td>
          <td>{{run.completed|default:"--"}}</td>
          <td>{{run.hosts|length}} / {{ run.finished_hosts }} / {{ run.errored_hosts }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}

    <form action="{{request.get_full_path}}" method="post">{% csrf_token %}
      <table class="table">
        {{form.as_table}}
        <tr>
          <td colspan="2">
            <button class="btn btn-primary"
                    type="submit">
              <span class="fa fa-plus"></span>
              {% trans "Create new run" %}
            </button>
          </td>
        </tr>
      </table>
    </form>
  </div>
</div>
{% endblock %}

script/templates/script/navbar.html
{% load i18n %}
<li class="dropdown">
  <a href="#" class="dropdown-toggle"
     data-toggle="dropdown" role="button"
     aria-haspopup="true" aria-expanded="false">
    <span class="fa {{app.font_awesome_class}}"></span>
    {{app.verbose_name}}
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li>
      <a href="{% url 'script:list' %}">
        <span class="fa fa-magic"></span>
        {% trans "All scripts" %}
      </a>
    </li>
    <li>
      <a href="{% url 'script:create' %}">
        <span class="fa fa-plus"></span>
        {% trans "Create new" %}</a>
    </li>
  </ul>
</li>

script/templates/script/script_base.html
{% extends "base.html" %}

{% block context_navbar %}
{% include "script/navbar.html" %}
{% endblock %}