auth/urls.py
from django.urls import re_path
from . import views


app_name = "auth"
urlpatterns = [
    re_path(r"^$", views.List.as_view(), name="list"),
    re_path(r"^edit/(?P<user>[^/]+)$", views.Edit.as_view(), name="edit"),
]

octonet/urls.py
from django.conf.urls import include
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r"^$", views.Home.as_view(), name="home"),
    re_path(r"^login/$", views.Login.as_view(), name="login"),
    re_path(r"^logout/$", views.Logout.as_view(), name="logout"),
    re_path(r"^newsfeed/$", views.NewsFeed.as_view(), name="newsfeed"),
    re_path(r"^veyon/client_conf$", views.VeyonClientConfiguration.as_view(), name="veyon-client-conf"),
    re_path(r"^octofussd-error/$", views.OctofussdError.as_view(), name="octofussd_error"),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r"^hostqueue/", include("hostqueue.urls", namespace="hostqueue")),
    re_path(r"^dhcp/", include("dhcp.urls", namespace="dhcp")),
    re_path(r"^polygen/", include("polygen.urls", namespace="polygen")),
    re_path(r"^firewall/", include("firewall.urls", namespace="firewall")),
    re_path(r"^dansguardian/", include("dansguardian.urls", namespace="dansguardian")),
    re_path(r"^host/", include("host.urls", namespace="host")),
    re_path(r"^upgrade/", include("upgrade.urls", namespace="upgrade")),
    re_path(r"^asterisk/", include("asterisk.urls", namespace="asterisk")),
    re_path(r"^samba/", include("samba.urls", namespace="samba")),
    re_path(r"^users/", include("users.urls", namespace="users")),
    re_path(r"^script/", include("script.urls", namespace="script")),
    re_path(r"^quota/", include("quota.urls", namespace="quota")),
    re_path(r"^printers/", include("printers.urls", namespace="printers")),
    re_path(r"^services/", include("services.urls", namespace="services")),
    re_path(r"^auth/", include("auth.urls", namespace="auth")),
    re_path(r"^fussmanager/", include("fussmanager.urls", namespace="fussmanager")),
]

services/urls.py
from django.urls import re_path
from django.views.generic import TemplateView
from . import views


app_name = "services"
urlpatterns = [
    re_path(r"^list$", views.List.as_view(), name="list"),
    re_path(r"^do/(?P<service>[-\w]+)/(?P<action>[a-z]+)$", views.PerformAction.as_view(), name="do"),
    # refs #13223
    re_path(r"^access_points/manage$", views.ManageAccessPoints.as_view(), name="manage_access_points"),
]

users/urls.py
from django.urls import re_path
from . import views


app_name="users"
urlpatterns = [
    re_path(r"^user/list$", views.UserList.as_view(), name="list"),
    re_path(r"^user/list_json", views.UserListJSON.as_view(), name="list_json"),
    re_path(r"^user/create", views.UserCreate.as_view(), name="user_create"),
    re_path(r"^user/(?P<uid>[^/]+)/detail$", views.UserDetail.as_view(), name="detail"),
    re_path(r"^user/(?P<uid>[^/]+)/edit$", views.UserEdit.as_view(), name="user_edit"),
    re_path(r"^user/(?P<uid>[^/]+)/set-enabled$", views.UserSetEnabled.as_view(), name="user_set_enabled"),
    # refs #12559
    # refs #14151: Hide the button that made POST to this view
    # re_path(r"^user/(?P<uid>[^/]+)/force-password-change$", views.UserForcePasswordChange.as_view(), name="user_force_password_change"),
    re_path(r"^user/(?P<uid>[^/]+)/add-group$", views.UserAddGroup.as_view(), name="user_add_group"),
    # refs #213
    re_path(r"^user/(?P<uid>[^/]+)/delete$", views.UserDelete.as_view(), name="user_delete"),
    re_path(r"^groups/list$", views.GroupList.as_view(), name="group_list"),
    # refs #212
    re_path(r"^group/create$", views.GroupCreate.as_view(), name="group_create"),
    re_path(r"^group/(?P<name>[^/]+)/detail$", views.GroupDetail.as_view(), name="group_detail"),
    re_path(r"^group/(?P<name>[^/]+)/edit$", views.GroupEdit.as_view(), name="group_edit"),
    re_path(r"^group/(?P<name>[^/]+)/add-group$", views.GroupAddGroup.as_view(), name="group_add_group"),
    re_path(r"^group/(?P<name>[^/]+)/remove-group$", views.GroupRemoveGroup.as_view(), name="group_remove_group"),
    re_path(r"^group/(?P<name>[^/]+)/drop-all-users$", views.GroupDropAllUsers.as_view(), name="group_drop_all_users"),
    re_path(r"^group/(?P<name>[^/]+)/add-permission$", views.GroupAddPermission.as_view(), name="group_add_perm"),
    re_path(r"^group/(?P<name>[^/]+)/remove-permission$", views.GroupRemovePermission.as_view(), name="group_remove_perm"),
    re_path(r"^group/(?P<name>[^/]+)/delete$", views.GroupDelete.as_view(), name="group_delete"),
    re_path(r"^csvimport$", views.CSVImport.as_view(), name="csvimport"),
    re_path(r"^csvimport_ajax$", views.CSVImportAJAX.as_view(), name="csvimport_ajax"),
    # refs #353
    re_path(r"^csvimport/check$", views.CSVImportCheck.as_view(), name="csvimport_check"),
    re_path(r"^masscreate$", views.MassCreate.as_view(), name="masscreate"),
    # refs #108
    re_path(r"^massedit$", views.MassEdit.as_view(), name="massedit"),
    re_path(r"^processldif", views.ProcessLDIF.as_view(), name="processldif"),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
# coding: utf-8
import codecs
from collections import defaultdict
import csv
import datetime
from html import unescape
import io
import json
import os
import re
from django import http, forms
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.utils import html
from django.utils.translation import gettext_lazy as _
from django.shortcuts import redirect, render
from django.views.generic import View, TemplateView
from django.views.generic.edit import FormView
from octofuss import exceptions as oexceptions
from octofuss import password as password_generator
from octonet.forms import FormControlClassMixin
from octonet.mixins import OctonetMixin
from octonet.utils import reorder_fields
from urllib.parse import quote_plus, unquote_plus


class UserList(OctonetMixin, TemplateView):
    template_name = "users/list.html"


class UserListJSON(OctonetMixin, View):
    def get(self, request, *args, **kw):
        tree = self.octofuss_tree("/users/users")
        users = tree.lget([])
        if users == None:
            users = []
        iTotalRecords = len(users)

        sEcho = request.GET.get('sEcho', None)
        sSearch = request.GET.get('sSearch', None)
        iDisplayStart = request.GET.get('iDisplayStart', None)
        iDisplayLength = request.GET.get('iDisplayLength', None)
        # refs #134
        iSortCol = request.GET.get('iSortCol_0', 1)
        sSortDir = request.GET.get('sSortDir_0', "asc")
        match = {
            0: "enabled",
            1: "uid",
            2: "gecos",
            3: "ou",
            4: "homeDirectory",
            5: "controllerGroup",
            6: "uidNumber",
        }

        if sSearch and users:
            users = [ u for u in users if sSearch in u.get("uid")]

        # refs #134, sort for real
        sort_key = match[int(iSortCol)] if iSortCol else "uid"
        users = sorted(
            users,
            key=lambda x: x.get(sort_key) if x.get(sort_key) is not None else "",
            reverse=(sSortDir == "desc"),
        )
        iTotalDisplayRecords = len(users)

        if iDisplayStart:
            start = int(iDisplayStart)
        else:
            start = 0
        if iDisplayLength:
            length = int(iDisplayLength)
        else:
            length = 30

        # refs #9972
        epoch = datetime.date(1970, 1, 1)
        today = datetime.date.today()

        aaData = []
        for u in users[start:start+length]:
            # refs #9972
            # Sometimes this get() will return None (as seen in test instances), so...
            shadowMax = int(u.get('shadowMax', 0) or 0)
            # This get didn't fail in test instances, but just to be on the safe side...
            shadowLastChange = int(u.get('shadowLastChange', 0) or 0)
            last_password_change = epoch + datetime.timedelta(days=shadowLastChange)
            next_password_change = last_password_change + datetime.timedelta(days=shadowMax)
            expired_password = shadowLastChange == 0 or next_password_change < today
            password_icon_color = expired_password and "text-danger" or "text-success"

            row = []
            row.append("<span class='glyphicon glyphicon-{}'></span>".format(
                u.get("enabled") and "ok text-success" or "remove text-danger"))
            row.append("<a href='{}'>{}</a>".format(
                html.escape(reverse("users:detail", kwargs=dict(uid=u.get("uid")))),
                html.escape(u.get("uid"))
            ))
            row.append(u.get("gecos"))
            # refs #9972
            row.append("<span class='fa fa-key {}'></span>".format(password_icon_color))
            row.append(u.get("ou"))
            row.append(u.get("homeDirectory"))
            controller = u.get("controllerGroup")
            if controller:
                row.append("<a href='{}'>{}</a>".format(
                    html.escape(reverse("users:group_detail", args=[controller])),
                    html.escape(controller))
                    )
            else:
                row.append("")
            row.append(u.get("uidNumber"))
            row.append("<a class='btn btn-primary btn-sm' href='{}'><span class='fa fa-pencil'></span> {}</a>".format(
                html.escape(reverse("users:user_edit", kwargs=dict(uid=u.get("uid")))),
                html.escape(_("Edit"))
                ))
            aaData.append(row)
        data = dict(aaData=aaData,
                    sEcho=sEcho,
                    iTotalDisplayRecords=iTotalDisplayRecords,
                    iTotalRecords=iTotalRecords
            )
        return http.HttpResponse(json.dumps(data), content_type="application/json")


class UserMixin(OctonetMixin):
    def load_objects(self):
        self.tree = self.octofuss_tree("/users/users/{}".format(self.kwargs["uid"]))
        self.user = self.tree.lget([])
        self.user["groups"] = self.tree.llist(["groups"])
        self.all_groups = self.root_tree.lget(["users", "groups"])
        self.user['get_gecos_display'] = unescape(self.user['gecos'])
        # refs #9972
        epoch = datetime.date(1970, 1, 1)
        today = datetime.date.today()
        # Sometimes this get() will return None (as seen in test instances), so...
        shadowMax = int(self.user.get('shadowMax', 0) or 0)
        # This get didn't fail in test instances, but just to be on the safe side...
        shadowLastChange = int(self.user.get('shadowLastChange', 0) or 0)
        last_password_change = epoch + datetime.timedelta(days=shadowLastChange)
        if shadowLastChange:
            self.user['last_password_change'] = last_password_change.strftime("%Y-%m-%d")
            self.user['last_password_change_days'] = _("{} day(s) ago").format((today - last_password_change).days)
        else:
            self.user['last_password_change'] = "-"
            self.user['last_password_change_days'] = _("0 day(s) ago")
        next_password_change = last_password_change + datetime.timedelta(days=shadowMax)
        self.user['next_password_change'] = next_password_change.strftime("%Y-%m-%d")
        if next_password_change < today:
            self.user['next_password_change_days'] = _("{} day(s) ago").format((today - next_password_change).days)
        elif next_password_change > today:
            self.user['next_password_change_days'] = _("in {} day(s)").format((next_password_change - today).days)
        else:
            self.user['next_password_change_days'] = _("Today!")

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        ctx["octofuss_user"] = self.user
        ctx["all_groups"] = self.all_groups
        return ctx


# refs #108
class MassEdit(OctonetMixin, FormView):
    template_name = "users/massedit.html"

    def load_objects(self):
        # refs #287
        self.has_quota = self.root_tree.lhas(["quota"])

    def dispatch(self, request, *args, **kwargs):
        self.uids = request.GET.get('uids', "")
        self.users = self.uids.split(",") or []
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        # refs #287
        if self.has_quota:
            return {
                "quota": [{"fs": fs} for fs in self.root_tree.llist(["quota"])]
            }
        else:
            return {}

    def get_form_class(self):
        all_groups = self.root_tree.llist(["users", "groups"])
        all_netperms = self.root_tree.llist(['netperms', 'bygroup'])

        class AddToGroupForm(FormControlClassMixin, forms.Form):
            add_to_group = forms.MultipleChoiceField(
                choices=[(x, unquote_plus(x)) for x in all_groups],
                label=_("Add to group"), required=False,
            )

        class RemoveFromGroupForm(FormControlClassMixin, forms.Form):
            remove_from_group = forms.MultipleChoiceField(
                choices=[(x, unquote_plus(x)) for x in all_groups],
                label=_("Remove from group"), required=False,
            )

        class NetPermForm(FormControlClassMixin, forms.Form):
            def __init__(self, *args, **kw):
                super().__init__(*args, **kw)
                self.fields["netperm"].choices = \
                    [("", _("Please choose..."))] +\
                    [(x, unquote_plus(x)) for x in all_netperms]

        class AddNetPermForm(FormControlClassMixin, forms.Form):
            add_netperm = forms.MultipleChoiceField(
                choices=[(x, unquote_plus(x)) for x in all_netperms],
                label=_("Add netperm"), required=False,
            )

        class RemoveNetPermForm(FormControlClassMixin, forms.Form):
            remove_netperm = forms.MultipleChoiceField(
                choices=[(x, unquote_plus(x)) for x in all_netperms],
                label=_("Remove netperm"), required=False,
            )

        # refs #287
        if self.has_quota:
            return make_multiform(**{
                'add_to_group': AddToGroupForm,
                'remove_from_group': RemoveFromGroupForm,
                'add_netperm': AddNetPermForm,
                'remove_netperm': RemoveNetPermForm,
                'quota': forms.formset_factory(OptionalQuotaForm, extra=0),
            })
        else:
            return make_multiform(**{
                'add_to_group': AddToGroupForm,
                'remove_from_group': RemoveFromGroupForm,
                'add_netperm': AddNetPermForm,
                'remove_netperm': RemoveNetPermForm,
            })

    def form_valid(self, form):
        uids = self.request.POST.get('uids', "").split(",")
        action = self.request.POST.get("action", "")
        if not action:
            messages.error(self.request, _("No action specified"))
            return redirect("users:list")
        if not uids:
            messages.error(self.request, _("No users specified"))
            return redirect("users:list")
        if action == "activate":

users/templates/users/group_actions.html
{% load i18n %}

<!-- code for users elimination -->
<script type="text/javascript">

$.ajaxSetup({
    beforeSend: function(xhr, settings) {
      xhr.setRequestHeader("X-CSRFToken", "{{csrf_token}}");
    }
});

function ajax_users_elimination() {
  $("#finish-alert").hide();
  $("#users-drop-modal").modal();
  $.ajax({
    type: "POST",
    url: "{% url 'users:group_drop_all_users' name=group.cn %}",
    data: {"csrfmiddlewaretoken": "{{ csrf_token }}"},
    dataType: "json",
    processData: false,
    contentType: false,
    xhrFields: {
      onprogress: function(e) {
        var all = e.currentTarget.response.split("\n");
        if (all.length > 2) {console.log(all);var current = JSON.parse(all[all.length-2]);}
        else {var current = JSON.parse(all[0]);}
        var act = parseInt(current["percentage"]);
        var pgbar = $("#pgbar");
        pgbar.attr("aria-valuenow", act);
        pgbar.css("width", "" + act + "%");
        $("#modal-deleted-user").text(current["lastDeleted"]);
        $("#total_users").text(current["totalUsers"]);
        if (current["finish"]) {
          $("#finish-alert").slideDown();
        }
      }
    },
  });
}

$(document).ready(function() {$("#drop-all-users-form").submit(ajax_users_elimination);})

</script>


<div class="modal" tabindex="-1" role="dialog" id="users-drop-modal" data-backdrop="static" data-keyboard="false"><!-- users drop modal -->
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title"><b>{% trans "Users elimination in progress... - DO NOT REFRESH THIS PAGE!" %}</b></h3>
      </div>
      <div class="modal-body">
        <a style="color:black;" id="modal-deleted-user">{% trans "Nothing" %}</a> {% trans "deleted" %}
        <br><br>
        <div class="progress">
          <div id="pgbar" class="progress-bar progress-bar-danger progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
          </div>
        </div>
        <div id="finish-alert" class="text-right">
          <div class="alert alert-success text-left" role="alert">
            <strong id="total_users"></strong> {% trans "users successfully deleted" %}.
          </div>
          <a href="#" onclick="location.reload();" class="btn btn-lg btn-warning">
            <i class="fa fa-close" aria-hidden="true"></i> &nbsp;
            {% trans "Close" %}
          </a>
        </div>
      </div>
    </div>
  </div>
</div><!-- end modal -->


<p>{% trans "Add all users of the group to a different group" %}</p>
<form method="post"
      class="form-inline"
      action="{% url 'users:group_add_group' name=group.cn %}">
  {% csrf_token %}
  <div class="form-group">
    <select name="group" class="form-control">
      {% for g in all_groups %}
      <option value="{{g.cn}}">{{g.cn}}</option>
      {% endfor %}
    </select>
    <button type=" submit" class="btn btn-primary">
      <span class="fa fa-plus"></span>
      {% trans "Add to group" %}
    </button>
  </div>
</form>

<p>{% trans "Remove all users from the group" %}</p>
<form method="post"
      class="form-inline"
      action="{% url 'users:group_remove_group' name=group.cn %}">
  {% csrf_token %}
  <div class="form-group">
    <select name="group" class="form-control hidden">
      {% for g in all_groups %}

      <option value="{{g.cn}}"
              {% if g == group %}
              SELECTED
              {% endif %}
              >{{g.cn}}</option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-primary btn-danger btn-block"
              onclick="if(confirm('{% trans "Are you sure you want to delete all users from this group?" %}')) { return true;} else {return false; }">
      <span class="fa fa-times"></span>
      {% trans "Remove" %}
    </button>
  </div>
</form>

<p>{% trans "Add permission to all group's members" %}</p>
<form method="post"
      class="form-inline"
      action="{% url 'users:group_add_perm' name=group.cn %}">
  {% csrf_token %}
  <div class="form-group">
    <select name="perm" class="form-control">
      {% for p in all_perms %}
      <option value="{{p}}">{{p}}</option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-primary">
      <span class="fa fa-plus"></span>
      {% trans "Add permission" %}
    </button>
  </div>
</form>

<p>{% trans "Remove permission from all group's members" %}</p>
<form method="post"
      class="form-inline"
      action="{% url 'users:group_remove_perm' name=group.cn %}">
  {% csrf_token %}
  <div class="form-group">
    <select name="perm" class="form-control">
      {% for p in all_perms %}
      <option value="{{p}}">{{p}}</option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-primary btn-danger">
      <span class="fa fa-times"></span>
      {% trans "Remove permission" %}
    </button>
  </div>
</form>
<br><br>
<p>{% trans "Delete all users in the group" %}</p>
<form method="post"
      class="form-inline"
      action="#"
      id="drop-all-users-form"
      onsubmit="return false;">
  {% csrf_token %}
  <div class="form-group">
    <select name="group" class="form-control hidden">
      {% for g in all_groups %}

      <option value="{{g.cn}}"
              {% if g == group %}
              SELECTED
              {% endif %}
              >{{g.cn}}</option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-primary btn-danger btn-block"
              onclick="if(confirm('{% trans "Are you sure you want to delete all the users belonging to this group?" %}')) { return true;} else {return false; }">
      <span class="fa fa-times"></span>
      {% trans "DELETE all users belonging to this group from the system" %}
    </button>
  </div>
</form>

{% if not form.group.members.value %}
<form method="post"
      class="form-inline"
      action="{% url 'users:group_delete' name=group.cn %}">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger" onclick="if(confirm('{% trans "Are you sure to delete this group?" %}')) { return true;} else {return false; }">
      <span class="fa fa-times"></span>
      {% trans "Delete Group" %}
    </button>
</form>
{% endif %}

users/templates/users/group_detail.html
{% extends "users/user_base.html" %}
{% load static %}
{% load i18n %}

{% block head %}
{{block.super}}
<link rel="stylesheet" href="{% static 'dt/datatables.min.css' %}"/>
<script src="{% static 'dt/datatables.min.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function() {
      $("#members_list").DataTable({
          language: {
              url:  "{% static 'dt/i18n/' %}{{LANGUAGE_CODE}}.lang"
          },

          pageLength: 25,

      });

  });
</script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-10">
    <h1>{% trans "Group" %}: {{group.cn}} ({{group.gidNumber}})</h1>
  </div>
  <div class="col-md-2">
    <a href="{% url 'users:group_edit' name=group.cn %}"
       class="btn btn-primary pull-right">
      <span class="fa fa-pencil"></span>
      {% trans "Edit" %}
    </a>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>{% trans "Members" %}</h2>
    <table class="table table-striped" id="members_list">
      <thead>
        <tr>
          <th>{% trans "Username" %}</th>
          <th>{% trans "Full name" %}</th>
        </tr>
      </thead>
      <tbody>
      {% for m in members %}
      <tr>
        <td>
          <a href="{% url 'users:detail' uid=m.uid %}">
            {{m.uid}}
          </a>
        </td>
        <td>{{m.get_gecos_display}}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

users/templates/users/group_list.html
{% extends "users/user_base.html" %}
{% load static %}
{% load i18n %}

{% block head %}
{{block.super}}
<link rel="stylesheet" href="{% static 'dt/datatables.min.css' %}"/>
<script src="{% static 'dt/datatables.min.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function() {
      $("#group_list").DataTable({
          language: {
              url:  "{% static 'dt/i18n/' %}{{LANGUAGE_CODE}}.lang"
          },

          pageLength: 25,
          "columnDefs": [ {
              "targets": 2,
              "orderable": false
          } ]

      });

  });
</script>
{% endblock %}


{% block content %}
<div class="row">
  <div class="col-md-9">
    <h1>{% trans "Groups" %}</h1>
  </div>
  <div class="col-md-3">
    <a href="{% url 'users:group_create' %}" class="btn btn-primary pull-right"><span class="fa fa-plus"></span> {% trans 'Create new group' %}</a>
  </div>
</div>

<table class="table table-striped" id="group_list">
  <thead>
    <tr>
      <th>{% trans "Group name" %}</th>
      <th>{% trans "GID" %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for g in groups %}
    <tr>
      <td>
        <a href="{% url 'users:group_detail' name=g.cn %}">
          {{g.cn}}
        </a>
      </td>
      <td>{{g.gidNumber}}</td>
      <td>
        <a href="{% url 'users:group_edit' name=g.cn %}"
           class="btn btn-primary btn-sm">
          <span class="fa fa-pencil"></span>
          {% trans "Edit" %}
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

users/templates/users/navbar.html
{% load i18n %}
<li class="dropdown">
  <a href="#" class="dropdown-toggle"
     data-toggle="dropdown" role="button"
     aria-haspopup="true" aria-expanded="false">
    <span class="fa {{app.font_awesome_class}}"></span>
    {{app.verbose_name}}
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li>
      <a href="{% url 'users:list' %}">
        <span class="fa fa-user"></span>
        {% trans "All users" %}
      </a>
    </li>
    <li>
      <a href="{% url 'users:user_create' %}">
        <span class="fa fa-user-plus"></span>
        {% trans "Create user" %}
      </a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="{% url 'users:csvimport_check' %}">
        <span class="fa fa-file-text-o"></span>
        {% trans "Check CSV file prior to import" %}
      </a>
    </li>
    <li>
      <a href="{% url 'users:processldif' %}">
        <span class="fa fa-id-badge"></span>
        {% trans "Convert LDIF File" %}
      </a>
    </li>
    <li>
      <a href="{% url 'users:csvimport' %}">
        <span class="fa fa-list-ul"></span>
        {% trans "Import from CSV" %}
      </a>
    </li>
    <li>
      <a href="{% url 'users:masscreate' %}">
        <span class="fa fa-user-plus"></span>
        {% trans "Mass Create" %}
      </a>
    </li>
    <li class="divider"></li>
    <li>
      <a href="{% url 'users:group_list' %}">
        <span class="fa fa-users"></span>
        {% trans "All Groups" %}
      </a>
    </li>
    <li>
      <a href="{% url 'users:group_create' %}">
        <span class="fa fa-plus"></span>
        {% trans 'Create new group' %}
      </a>
    </li>
    {# refs #13826 #}
    <li class="divider"></li>
    <li>
      {#<a href="{% url 'users:propagate_net_perm' %}">#}
      {% if "users/user/list" in request.META.HTTP_REFERER %}
        <a href="{% url 'services:do' service="propagate-net-perm" action="restart" %}">
          <span class="fa fa-reply-all fa-flip-horizontal"></span>
          {% trans "Propagate network access permission" %}
        </a>
      {% else %}
        <a href="{% url 'services:do' service="propagate-net-perm" action="restart" %}?from=users_menu">
          <span class="fa fa-reply-all fa-flip-horizontal"></span>
          {% trans "Propagate network access permission" %}
        </a>
      {% endif %}
    </li>
  </ul>
</li>

users/templates/users/process_ldif.html
{% extends "users/user_base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
<h1>{% trans "Process LDIF File" %}</h1>

<div class="row" id="id_form_row">
  <div class="col-md-12">
    <div class="well">
      {% blocktrans %}
      This tool allows you to upload an LDIF file, and have it converted to CSV
      format, suitable for import in Octonet.

      <strong>Password will be randomly generated</strong>

      {% endblocktrans %}
    </div>

    <form id="id_form" method="post" enctype="multipart/form-data" action="{% url "users:processldif" %}" role="form">
      {% csrf_token %}
      <table class="table">
        {{form.as_table}}
        <tr>
          <td colspan="2">
            <button type="submit" class="btn btn-primary" id="upload">
              <span class="fa fa-upload"></span>
              {% trans "Generate CSV File" %}
            </button>
          </td>
        </tr>
      </table>
    </form>

    <a id="csv_import_link"
       class="btn btn-danger" style="display: none;"
       href="{% url "users:csvimport" %}">
      <span class="fa fa-upload"></span>
      {% trans "Import the generated file" %}
    </a>
    <script type="text/javascript">
      $(function() {
      $("#upload").click(function () {
      $("#csv_import_link").show();
      });
      });
    </script>
  </div>
</div>
{% endblock %}

users/templates/users/user_base.html
{% extends "base.html" %}

{% block context_navbar %}
{% include "users/navbar.html" %}
{% endblock %}