auth/urls.py
from django.urls import re_path
from . import views


app_name = "auth"
urlpatterns = [
    re_path(r"^$", views.List.as_view(), name="list"),
    re_path(r"^edit/(?P<user>[^/]+)$", views.Edit.as_view(), name="edit"),
]

octonet/urls.py
from django.conf.urls import include
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r"^$", views.Home.as_view(), name="home"),
    re_path(r"^login/$", views.Login.as_view(), name="login"),
    re_path(r"^logout/$", views.Logout.as_view(), name="logout"),
    re_path(r"^newsfeed/$", views.NewsFeed.as_view(), name="newsfeed"),
    re_path(r"^veyon/client_conf$", views.VeyonClientConfiguration.as_view(), name="veyon-client-conf"),
    re_path(r"^octofussd-error/$", views.OctofussdError.as_view(), name="octofussd_error"),
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    re_path(r"^hostqueue/", include("hostqueue.urls", namespace="hostqueue")),
    re_path(r"^dhcp/", include("dhcp.urls", namespace="dhcp")),
    re_path(r"^polygen/", include("polygen.urls", namespace="polygen")),
    re_path(r"^firewall/", include("firewall.urls", namespace="firewall")),
    re_path(r"^dansguardian/", include("dansguardian.urls", namespace="dansguardian")),
    re_path(r"^host/", include("host.urls", namespace="host")),
    re_path(r"^upgrade/", include("upgrade.urls", namespace="upgrade")),
    re_path(r"^asterisk/", include("asterisk.urls", namespace="asterisk")),
    re_path(r"^samba/", include("samba.urls", namespace="samba")),
    re_path(r"^users/", include("users.urls", namespace="users")),
    re_path(r"^script/", include("script.urls", namespace="script")),
    re_path(r"^quota/", include("quota.urls", namespace="quota")),
    re_path(r"^printers/", include("printers.urls", namespace="printers")),
    re_path(r"^services/", include("services.urls", namespace="services")),
    re_path(r"^auth/", include("auth.urls", namespace="auth")),
    re_path(r"^fussmanager/", include("fussmanager.urls", namespace="fussmanager")),
]

upgrade/urls.py
from django.urls import re_path
from . import views

app_name = "upgrade"
urlpatterns = [
    re_path(r"^$", views.List.as_view(), name="list"),
    re_path(r"^edit/(?P<name>[^/]+)$", views.Edit.as_view(), name="edit"),
    re_path(r"^schedule/(?P<name>[^/]+)$", views.Schedule.as_view(), name="schedule"),
    re_path(r"^delete/(?P<name>[^/]+)$", views.Delete.as_view(), name="delete"),
    re_path(r"^update/(?P<name>[^/]+)$", views.Update.as_view(), name="update"),
    re_path(r"^complete/(?P<domain>[^/]+)$", views.Complete.as_view(), name="complete"),
    re_path(r"^hosts/add/(?P<name>[^/]+)$", views.AddHost.as_view(), name="add_host"),
    re_path(r"^hosts/remove/(?P<name>[^/]+)$", views.RemoveHost.as_view(), name="remove_host"),
    re_path(r"^hosts/addgroup/(?P<name>[^/]+)$", views.AddGroup.as_view(), name="add_group"),
    re_path(r"^hosts/removegroup/(?P<name>[^/]+)$", views.RemoveGroup.as_view(), name="remove_group"),
]

upgrade/models.py
from django.db import models

# Create your models here.

upgrade/views.py
from django.utils.translation import gettext_lazy as _
from django import http, forms
from django.views.generic import View, TemplateView
from django.views.generic.edit import FormView
from django.contrib import messages
from django.shortcuts import redirect
from octonet.mixins import OctonetMixin
from octonet.forms import FormControlClassMixin
from urllib.parse import quote_plus, unquote_plus

#def upgrade_cmp(a, b):
#    res = cmp(a["completed"], b["completed"])
#    if res != 0: return res
#    res = cmp(a["scheduled"], b["scheduled"])
#    if res != 0: return res
#    return cmp(a["name"], b["name"])
#

class NewForm(FormControlClassMixin, forms.Form):
    name = forms.CharField(label=_("Name"), required=True)


class List(OctonetMixin, FormView):
    template_name = "upgrade/list.html"
    form_class = NewForm

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        tree = self.octofuss_tree("/upgrades")
        udata = tree.get("")
        for u in udata:
            u["quoted_name"] = u["name"]
            u["name"] = unquote_plus(u["name"])
        udata.sort(key=lambda x:(x["completed"] or "", x["scheduled"] or "", x["name"]))
        ctx["udata"] = udata
        return ctx

    def form_valid(self, form):
        tree = self.octofuss_tree("/upgrades")
        new_name = quote_plus(form.cleaned_data["name"])
        try:
            tree.create(new_name)
        except Exception as e:
            messages.error(self.request, _("Cannot create {}: {}").format(new_name, str(e)))
            return redirect("upgrade:list")
        return redirect("upgrade:edit", name=new_name)


class UpgradeMixin(OctonetMixin):
    def load_objects(self):
        super().load_objects()
        self.name = self.kwargs["name"]
        self.tree = self.octofuss_tree("/upgrades/" + self.name)
        self.upgrade = self.tree.get("")

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        ctx["name"] = self.name
        ctx["upgrade"] = self.upgrade
        return ctx


class Edit(UpgradeMixin, TemplateView):
    template_name = "upgrade/edit.html"

    def get_context_data(self, **kw):
        ctx = super().get_context_data(**kw)
        ctx.update(
#                update_form = update_form,
#                new_group_form = new_group_form,
#                del_group_form = del_group_form,
        )
        return ctx


class Schedule(UpgradeMixin, View):
    def post(self, request, *args, **kw):
        if not self.upgrade["hosts"]:
            messages.error(self.request, _("Cannot schedule an upgrade without hosts"))
            return redirect("upgrade:edit", name=self.name)

        if self.upgrade["scheduled"]:
            messages.error(self.request, _("The upgrade has already been scheduled"))
            return redirect("upgrade:edit", name=self.name)

        try:
            self.tree.set("scheduled", True)
        except Exception as e:
            messages.error(self.request, _("Cannot schedule {}: {}").format(self.name, str(e)))

        return redirect("upgrade:edit", name=self.name)


class AddHost(UpgradeMixin, View):
    def post(self, request, *args, **kw):
        host = self.request.POST.get("host", None)
        if not host:
            messages.error(self.request, _("No host specified"))
            return redirect("upgrade:edit", name=self.name)

        host = quote_plus(host)
        try:
            self.tree.lcreate(["hosts", host])
        except Exception as e:
            messages.error(self.request, _("Cannot add host {}: {}").format(host, str(e)))

        return redirect("upgrade:edit", name=self.name)

#class NewHostForm(widgets.SingleFieldForm):
#    class FieldList(WidgetsList):
#        host = AutoCompleteField(
#                label = "Add host",
#                search_controller="../../search/hosts/",
#                search_param="name",
#                result_name="names")
#    name="newhostform"
#    fields = FieldList()
#    submit_text = _("Add")


class RemoveHost(UpgradeMixin, View):
    def post(self, request, *args, **kw):
        host = self.request.POST.get("host", None)
        if not host:
            messages.error(self.request, _("No host specified"))
            return redirect("upgrade:edit", name=self.name)

        host = quote_plus(host)
        try:
            self.tree.ldelete(["hosts", host])
        except Exception as e:
            messages.error(self.request, _("Cannot remove host {}: {}").format(host, str(e)))

        return redirect("upgrade:edit", name=self.name)


class AddGroup(UpgradeMixin, View):
    def post(self, request, *args, **kw):
        group = self.request.POST.get("group", None)
        if not group:
            messages.error(self.request, _("No group specified"))
            return redirect("upgrade:edit", name=self.name)

        try:
            hosts = self.root_tree.llist(["cluster", group])
        except Exception as e:
            messages.error(self.request, _("Cannot list hosts for group {}: {}").format(group, str(e)))
            return redirect("upgrade:edit", name=self.name)

        for host in hosts:
            if host[0] == ":": continue
            try:
                self.tree.lcreate(["hosts", host])
            except Exception as e:
                messages.error(self.request, _("Cannot add host {}: {}").format(host, str(e)))

        return redirect("upgrade:edit", name=self.name)


class RemoveGroup(UpgradeMixin, View):
    def post(self, request, *args, **kw):
        group = self.request.POST.get("group", None)
        if not group:
            messages.error(self.request, _("No group specified"))
            return redirect("upgrade:edit", name=self.name)

        try:
            hosts = self.root_tree.llist(["cluster", group])
        except Exception as e:
            messages.error(self.request, _("Cannot list hosts for group {}: {}").format(group, str(e)))
            return redirect("upgrade:edit", name=self.name)

        for host in hosts:
            if host[0] == ":": continue
            try:
                if not self.tree.lhas(["hosts", host]):
                    continue
            except Exception as e:
                messages.error(self.request, _("Cannot check if host {} is in the group: {}").format(host, str(e)))

            try:
                self.tree.ldelete(["hosts", host])
            except Exception as e:
                messages.error(self.request, _("Cannot remove host {}: {}").format(host, str(e)))

        return redirect("upgrade:edit", name=self.name)


class Delete(UpgradeMixin, View):
    def post(self, request, *args, **kw):
        info = self.tree.get("")

        if info["scheduled"] and not info["completed"]:
            messages.error(self.request, _("Cannot delete {} because it is currently scheduled and not yet completed").format(self.name))
            return redirect("upgrade:edit", name=self.name)
        else:
            self.tree.delete("")
            return redirect("upgrade:list")


class Update(UpgradeMixin, View):
    def post(self, request, *args, **kw):
        upgrade_type = self.request.POST.get("type", None)
        if upgrade_type not in ["upgrade", "dist-upgrade"]:
            messages.error(self.request, _("{} is not a valid type for upgrade {}").format(upgrade_type, self.name))
            return redirect("upgrade:edit", name=self.name)
        self.tree.set("type", upgrade_type)
        return redirect("upgrade:edit", name=self.name)


class Complete(OctonetMixin, View):
    ROOTS = {
        "hosts": "/computers",
        "groups": "/cluster",
    }

    def get(self, request, *args, **kw):
        name = self.request.GET.get("name", "")
        domain = self.kwargs.get("domain", None)
        root = self.ROOTS.get(domain, None)
        if root is None: raise http.Http404()
        tree = self.octofuss_tree(root)
        return http.JsonResponse({
            "names": [n for n in tree.list("") if n.lower().startswith(name.lower())],
        })

upgrade/templates/upgrade/edit.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Upgrade management" %}{% endblock %}

{% block context_navbar %}
<li class="dropdown">
  <a href="#" class="dropdown-toggle"
     data-toggle="dropdown" role="button"
     aria-haspopup="true" aria-expanded="false">
    {% trans "Upgrades"%}
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li>
      <a href="{% url 'upgrade:list' %}">
        {% trans "All upgrades" %}
      </a>
    </li>
  </ul>
</li>
{% endblock %}


{% block head %}
{{block.super}}
<script src="{% static 'typeahead-0.11.1/typeahead.bundle.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/typeaheadjs.css' %}"/>
<link rel="stylesheet" href="{% static 'dt/datatables.min.css' %}"/>
<script src="{% static 'dt/datatables.min.js' %}"></script>

<script type="text/javascript">
(function($) {
"use strict";

function main()
{
    $("#host_table").DataTable({
        paging: false,
        language: {
            url:  "{% static 'dt/i18n/' %}{{LANGUAGE_CODE}}.lang"
        }
    });

  var hosts = new Bloodhound({
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    datumTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
      url: "{% url 'upgrade:complete' domain='hosts' %}",
      transform: function(response) {
        return $.map(response.names, function(name) {
          return { value: name };
        });
      },
    },
  });

  var groups = new Bloodhound({
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    datumTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
      url: "{% url 'upgrade:complete' domain='groups' %}",
      transform: function(response) {
        return $.map(response.names, function(name) {
          return { value: name };
        });
      },
    },
  });

  $("#add_host_name").typeahead({
    minLength: 1,
    highlight: true,
  }, {
    name: "hosts",
    source: hosts,
    display: 'value',
  });

  $("#add_group_name").typeahead({
    minLength: 1,
    highlight: true,
  }, {
    name: "groups",
    source: groups,
    display: 'value',
  });


  $("#remove_group_name").typeahead({
    minLength: 1,
    highlight: true,
  }, {
    name: "groups",
    source: groups,
    display: 'value',
  });
}

$(main);
})(jQuery);
</script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    {% if upgrade.completed or not upgrade.scheduled %}
    <div class="pull-right">
      <form action="{% url "upgrade:delete" name=name %}" method="post">{% csrf_token %}
        <button type="submit" class="btn btn-danger">
          <span class="glyphicon glyphicon-remove"></span>
          {% trans "Delete" %}
        </button>
      </form>
    </div>
    {% endif %}

    <h1>
      {% if upgrade.scheduled %}
      {% blocktrans with name=name %}Upgrade: {{name}}{% endblocktrans %}
      {% else %}
      {% blocktrans with name=name %}Edit upgrade {{name}}{% endblocktrans %}
      {% endif %}
    </h1>

    {% if upgrade.scheduled %}
    <span class="label label-default">
      {% blocktrans with time=upgrade.scheduled %}
      Scheduled at <b>{{time}}</b>
      {% endblocktrans %}
    </span>
    {% endif %}

    {% if upgrade.completed %}
    <span class="label label-success">
      {% blocktrans with time=upgrade.completed %}
      Completed at <b>{{time}}</b>
      {% endblocktrans %}
    </span>
    {% else %}
    <span class="label label-danger">
      {% trans "Not completed yet" %}
    </span>
    {% endif %}

    {% if not upgrade.scheduled %}
    {% if upgrade.hosts %}
    <div class="pull-right">
    <form action="{% url "upgrade:schedule" name=name %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-success">
        {% trans "Schedule" %}
      </button>
    </form>
    </div>
    {% endif %}
    {% endif %}
  </div>
</div>
<div class="row">
    <div class="col-md-6">
    {% if not upgrade.scheduled %}

    <form action="{% url "upgrade:update" name=name %}" method="post" class="form-inline">
      {% csrf_token %}
      <label for="upgrade-type">{% trans "Update type:" %}</label>
      <select name="type" id="upgrade-type" class="form-control">
        <option value="upgrade"{% if upgrade.type == "upgrade" %} selected{% endif %}>{% trans "upgrade" %}</option>
        <option value="dist-upgrade"{% if upgrade.type == "dist-upgrade" %} selected{% endif %}>{% trans "dist-upgrade" %}</option>
      </select>
      <button type="submit" class="btn btn-default btn-sm"> {% trans "Change" %}</button>
    </form>

    <form action="{% url "upgrade:add_host" name=name %}" method="post" class="form-inline">
      {% csrf_token %}
      <label for="add_host_name">{% trans "Add host:" %}</label>
      <input id="add_host_name" type="text" name="host"
             class="form-control"
             placeholder="{% trans 'Host name' %}"></input>

      <button type="submit" class="btn btn-sm btn-default">
        {% trans "Add" %}
      </button>
    </form>

    <form action="{% url "upgrade:add_group" name=name %}" method="post"
          class="form-inline">
      {% csrf_token %}
      <label for="add_group_name">{% trans "Add group:" %}</label>
      <input id="add_group_name" type="text" name="group"
             placeholder="{% trans 'Group name'  %}"
             class="form-control">
      </input>
      <button type="submit" class="btn btn-sm btn-default">{% trans "Add" %}</button>
    </form>

    <form action="{% url "upgrade:remove_group" name=name %}" method="post"
          class="form-inline">
      {% csrf_token %}
      <label for="remove_group_name">{% trans "Remove group:" %}</label>
      <input id="remove_group_name" type="text" name="group"
             placeholder="{% trans 'Group name' %}"
             class="form-control"
             ></input>
      <button type="submit" class="btn btn-sm btn-default">
        {% trans "Remove" %}
      </button>
    </form>
    {% endif %}
  </div>
  <div class="col-md-6">
    <h2>{% trans "Host list" %}</h2>
    <table class="table table-striped" id="host_table">
      {% if not upgrade.scheduled %}
      <thead>
        <th>{% trans "Hostname" %}</th>
        <th></th>
      </thead>
      <tbody>
      {% for h in upgrade.hosts %}
      <tr>
        <td>{{h.name}}</td>
        <td>
        <form action="{% url "upgrade:remove_host" name=name %}" method="post">{% csrf_token %}
          <input type="hidden" name="host" value="{{h.name}}"></input>
          <button class="btn btn-sm btn-danger" type="submit">
            <span class="glyphicon glyphicon-remove"></span>
            {% trans "Remove" %}
          </button>
        </form>
        </td>
      </tr>
      {% endfor %}
      </tbody>
    {% else %}
      <thead>
        <tr>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Started" %}</th>
          <th>{% trans "Ended" %}</th>
          <th>{% trans "Result" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for h in upgrade.hosts %}
        <tr>
          <td>{{h.name}}</td>
          <td>{{h.started|default:"--"}}</td>
          <td>{{h.ended|default:"--"}}</td>
          <td>
            {% if h.result == 0 %}
            {% trans "Ok" %}
            {% elif not h.result %}
            --
            {% else %}
            {{h.result}}
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    {% endif %}
    </table>
  </div>

</div>
{% endblock %}

upgrade/templates/upgrade/list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "List of upgrades" %}{% endblock %}
{% block head %}
{{block.super}}
<link rel="stylesheet" href="{% static 'dt/datatables.min.css' %}"/>
<script src="{% static 'dt/datatables.min.js' %}"></script>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h1>{% trans "List of upgrades" %}</h1>
    <table class="table table-striped" id="upgrade_table">
      <thead>
        <tr>
          <th>{% trans "Name" %}</th>
          <th>{% trans "Type" %}</th>
          <th>{% trans "Scheduled" %}</th>
          <th>{% trans "Completed" %}</th>
          <th>{% trans "Number of hosts" %}</th>
        </tr>
      </thead>
        {% for u in udata %}
        <tr>
          <td><a href="{% url 'upgrade:edit' name=u.quoted_name %}">{{u.name}}</a></td>
          <td class="u_type">{{u.type}}</td>
          <td class="u_sche">{{u.scheduled|default:"--"}}</td>
          <td class="u_comp">{{u.completed|default:"--"}}</td>
          <td class="u_hosts" align="right">{{u.hosts|length}}</td>
        </tr>
        {% endfor %}
    </table>
    <script type="text/javascript">
    $(document).ready(function() {
        $("#upgrade_table").DataTable({
            language: {
                url:  "{% static 'dt/i18n/' %}{{LANGUAGE_CODE}}.lang"
            }
        });
    });
    </script>
    <h2>{% trans "Create new upgrade" %}</h2>
    <form action="." method="post" class="form-inline">
      {% csrf_token %}
      {{form}}
      <button class="btn btn-default" type="submit">
        <span class="glyphicon glyphicon-plus-sign"></span>
        {% trans "Create" %}
      </button>
    </form>
  </div>
</div>
{% endblock %}